language: docker

services:
  - docker

cache:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-frontend cnlan1/udagram-frontend
  - docker tag udagram-api-feed cnlan1/udagram-api-feed
  - docker tag udagram-api-user cnlan1/udagram-api-user
  - docker tag reverseproxy cnlan1/reverseproxy

after_success:
  - docker push cnlan1/udagram-api-feed
  - docker push cnlan1/udagram-api-user
  - docker push cnlan1/udagram-frontend
  - docker push cnlan1/udagram-reverseproxy

